version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=your_database
      - DB_USER=your_user
      - DB_PASS=your_password
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "12312:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
