name: CI/CD Pipeline with Podman

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Podman image
        run: podman build -t my-app-image .  
      - name: Run tests and linters
        run: |
          podman run my-app-image python -m unittest discover  # Run your tests
          podman run my-app-image flake8 app.py create_db.py    # Run your linter
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.VM_USER }}/deploy
            ./deploy.sh
