name: CI/CD Pipeline with Podman

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build and start services using Podman Compose
      - name: Start services using Podman Compose
        run: podman-compose up -d  # Start the web and db services

      # Step 3: Initialize the database
      - name: Initialize database
        run: podman-compose exec web python create_db.py  # Run your database setup script inside the web container

      # Step 4: Run tests inside the Podman container
      - name: Run tests and linters
        run: |
          podman-compose exec web python -m unittest discover  # Run your tests
          podman-compose exec web flake8 app.py create_db.py    # Run your linter

      # Step 5: Stop and clean up containers
      - name: Clean up
        run: podman-compose down -v
