name: CI/CD Pipeline with Podman

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean up existing containers
        run: |
          podman stop $(podman ps -aq) || true
          podman rm $(podman ps -aq) || true

      - name: Build Podman image
        run: |
          podman build -t my-app-image .

      - name: Run Application Container
        run: |
          podman run -d --name web -e DB_HOST=localhost -e DB_PORT=5432 -e DB_NAME=your_database -e DB_USER=your_user -e DB_PASS=your_password -p 5000:5000 my-app-image

      - name: Wait for Database to be Ready
        run: |
          until pg_isready -h localhost -U your_user -d your_database -p 5432; do
            sleep 2
          done

      - name: Run tests and linters
        run: |
          podman exec web python -m unittest discover
          podman exec web flake8 app.py create_db.py

      - name: Clean up after tests
        run: |
          podman stop web
          podman rm web
