name: CI/CD Pipeline with Podman

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Podman
      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman podman-compose

      # Step 3: Build and start containers using Podman Compose
      - name: Start services using Podman Compose
        run: |
          podman-compose up -d  # Start the web and db services

      # Step 4: Run tests in the web container
      - name: Run tests and linters
        run: |
          podman-compose exec web python -m unittest discover  # Run your tests
          podman-compose exec web flake8 app.py create_db.py    # Run your linter

      # Step 5: Stop and clean up containers
      - name: Clean up
        run: podman-compose down -v
