name: CI/CD Pipeline with Podman

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Start Services
        run: |
          podman-compose up -d --build
          sleep 5  # Wait for the application to start

      - name: Run tests
        run: |
          podman-compose exec web python -m unittest discover

      - name: Check Application Health
        run: |
          podman-compose exec web curl -f http://localhost:5000/health || exit 1

      - name: Deploy Project
        if: success()
        run: |
          echo "Deploying project..."
          # Add your deployment commands here

      - name: Clean up after tests
        run: |
          podman-compose down -v
