name: CI/CD Pipeline with Podman

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Podman image
        run: podman build -t my-app-image .  
      - name: Run tests and linters
        run: |
          podman run my-app-image python -m unittest discover  # Run your tests
          podman run my-app-image flake8 app.py create_db.py    # Run your linter
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to VM via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} 'cd /home/${{ secrets.VM_USER }}/deploy && ./deploy.sh'
