name: CI/CD Pipeline with Podman

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build and run the web and db containers manually using Podman
      - name: Build Podman image
        run: |
          podman build -t my-app-image .
          podman run -d --name db -e POSTGRES_DB=your_database -e POSTGRES_USER=your_user -e POSTGRES_PASSWORD=your_password -p 5432:5432 postgres:13
          podman run -d --name web -e DB_HOST=db -e DB_NAME=your_database -e DB_USER=your_user -e DB_PASS=your_password -p 5000:5000 my-app-image

      # Step 3: Initialize the database
      - name: Initialize database
        run: podman exec web python create_db.py  # Run your database setup script inside the web container

      # Step 4: Run tests and linters inside the Podman container
      - name: Run tests and linters
        run: |
          podman exec web python -m unittest discover  # Run your tests
          podman exec web flake8 app.py create_db.py    # Run your linter

      # Step 5: Stop and clean up containers
      - name: Clean up
        run: |
          podman stop web db
          podman rm web db
