name: CI/CD Pipeline with Podman

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean up existing containers
        run: |
          podman stop $(podman ps -aq) || true
          podman rm $(podman ps -aq) || true

      - name: Build Podman image
        run: |
          podman build -t my-app-image .

      - name: Run tests and linters
        run: |
          podman exec web python -m unittest discover
          
      - name: Clean up after tests
        run: |
          podman stop web
          podman rm web
