name: CI/CD Pipeline with Podman

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Podman image
        run: |
          podman build -t my-app-image .

      - name: Run Application Container
        run: |
          podman start web || podman run -d --name web --network=host \
            -e DB_HOST=localhost \
            -e DB_PORT=5432 \
            -e DB_NAME=your_database \
            -e DB_USER=your_user \
            -e DB_PASS=your_password \
            my-app-image
          sleep 5  # Wait for the application to start

      - name: Run tests
        run: |
          podman exec web python -m unittest discover

      - name: Check Application Health
        run: |
          podman exec web curl -f http://localhost:5000/health || exit 1

      - name: Deploy Project
        if: success()
        run: |
          echo "Deploying project..."
          # Add your deployment commands here

      - name: Clean up after tests
        run: |
          podman stop web
          podman rm web
