name: CI/CD Pipeline with Podman

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Podman image
        run: podman build -t your-image-name .

      - name: Run tests and linters
        run: |
          podman run your-image-name python -m unittest discover
          podman run your-image-name flake8 app.py create_db.py

      - name: Push image to container registry (Docker Hub)
        run: |
          podman login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
          podman tag your-image-name docker.io/your-dockerhub-username/your-image-name
          podman push docker.io/your-dockerhub-username/your-image-name

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/your-username/deploy
            ./deploy.sh
